# Generated by Django 2.2.5 on 2019-11-02 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and Time when the object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and Time when the object was last modified.')),
                ('content', models.TextField()),
                ('user', models.ForeignKey(help_text='User related to the blog.', on_delete=django.db.models.deletion.CASCADE, related_name='user_blog', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
    ]
