# Generated by Django 2.2.5 on 2019-11-02 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(help_text='Blog related to the comment.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_comment', to='blog.Blog'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and Time when the object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and Time when the object was last modified.')),
                ('blog', models.ForeignKey(help_text='Blog related to the like.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_like', to='blog.Blog')),
                ('user', models.ForeignKey(help_text='User related to the like.', on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Like',
            },
        ),
    ]
